name: ${project.name}
main: ${project.groupId}.${project.name}
version: ${project.version}
author: Packet
depend: [Lib]
commands:
  ping:
    description: PONG!
  pong:
    description: PING!